version: "3.1"
services:
  database:
    container_name: jdbc
    image: mariadb:10.5
    ports:
      - "3320:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=jdbc"

    volumes:
      - ./data:/var/lib/mysql
